/******************************************************************************\
 * Technische Universitaet Darmstadt, Institut fuer Nachrichtentechnik
 * Copyright (c) 2001
 *
 * Author(s):
 *	Volker Fischer
 *
 * Description:
 *	
 *
 ******************************************************************************
 *
 * This program is free software; you can redistribute it and/or modify it under
 * the terms of the GNU General Public License as published by the Free Software
 * Foundation; either version 2 of the License, or (at your option) any later 
 * version.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT 
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU General Public License for more 
 * details.
 *
 * You should have received a copy of the GNU General Public License along with
 * this program; if not, write to the Free Software Foundation, Inc., 
 * 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA
 *
\******************************************************************************/

#include <qlistview.h>
#include <qpixmap.h>
#include <qbuttongroup.h>
#include <qradiobutton.h>
#include <qtimer.h>
#include <qmessagebox.h>
#include <qcombobox.h>
#include <qurloperator.h>
#include <qnetworkprotocol.h>
#include <qdir.h>
#include <qmenubar.h>
#include <qpopupmenu.h>
#include <qlayout.h>
#include <qftp.h>
#include <qthread.h>

#ifdef _WIN32
# include "../../Windows/moc/StationsDlgbase.h"
#else
# include "moc/StationsDlgbase.h"
#endif
#include "../DrmReceiver.h"
#include "../Vector.h"

extern CDRMReceiver	DRMReceiver;


/* Definitions ****************************************************************/
/* Define the timer interval of updating the list view */
#define GUI_TIMER_LIST_VIEW_STAT		30000 /* ms (30 seconds) */

/* Location of the newest DRM schedule ini-file "DRMSchedule.ini". This file
   is generated by Klaus Schneider which is the administrator of
   www.drm-dx.de */
#define DRM_SCHEDULE_UPDATE_FILE		"ftp://216.92.35.131/DRMSchedule.ini"


/* Classes ********************************************************************/
class CStationsItem
{
public:
	int GetStartTimeNum() {return iStartHour * 100 + iStartMinute;}
	int GetStopTimeNum() {return iStopHour * 100 + iStopMinute;}
	void SetStartTimeNum(const int iStartTime)
	{
		/* Recover hours and minutes */
		iStartHour = iStartTime / 100;
		iStartMinute = iStartTime - iStartHour * 100;
	}
	void SetStopTimeNum(const int iStopTime)
	{
		/* Recover hours and minutes */
		iStopHour = iStopTime / 100;
		iStopMinute = iStopTime - iStopHour * 100;
	}

	int		iStartHour;
	int		iStartMinute;
	int		iStopHour;
	int		iStopMinute;
	int		iFreq;
	int		iDays;
	string	strName;
	string	strTarget;
	string	strLanguage;
	string	strSite;
	string	strCountry;
	_REAL	rPower;
};


class CDRMSchedule
{
public:
	CDRMSchedule();
	virtual ~CDRMSchedule() {}

	void ReadStatTabFromFile(const string strFileName);
	void WriteStatTabToFile(const string strFileName);

	int GetStationNumber() {return StationsTable.Size();}
	CStationsItem& GetItem(int const iPos) {return StationsTable[iPos];}
	_BOOLEAN IsActive(int const iPos);

protected:
	CVector<CStationsItem> StationsTable;
};


class MyListViewItem : public QListViewItem
{
public:
	MyListViewItem(QListView* parent, QString s1, QString s2 = QString::null,
		QString s3 = QString::null, QString s4 = QString::null,
		QString s5 = QString::null, QString s6 = QString::null,
		QString s7 = QString::null, QString s8 = QString::null) :
		QListViewItem(parent, s1, s2, s3, s4, s5, s6, s7, s8) {}

	/* Custom "key()" function for correct sorting behaviour */
	virtual QString key(int column, bool ascending) const;
};


class StationsDlg : public CStationsDlgBase
{
	Q_OBJECT

public:
	StationsDlg(QWidget* parent = 0, const char* name = 0, bool modal = FALSE,
		WFlags f = 0);
	virtual ~StationsDlg() {}

protected:
	enum ERemotecntr {RC_NOREMCNTR, RC_WINRADIO, RC_AOR7030, RC_ELEKTOR304};
	_BOOLEAN		SetFrequencyWinradio(const int iFreqkHz);
	_BOOLEAN		SetFrequencyAOR7030(const int iFreqkHz);
	_BOOLEAN		SetFrequencyElektor304(const int iFreqkHz);
#ifdef _WIN32
	void			OutputElektor304(HANDLE hCom, const _UINT32BIT iData);
	_REAL			TimeReadElektor304();
	void			DelayElektor304(_REAL rDelay);
#endif

	void			SetStationsView();
    virtual void	showEvent(QShowEvent* pEvent);

	CDRMSchedule	DRMSchedule;
	QPixmap			BitmCubeGreen;
	QPixmap			BitmCubeYellow;
	QPixmap			BitmCubeRed;
	QTimer			Timer;
	_BOOLEAN		bShowAll;
	ERemotecntr		eWhichRemoteControl;
	QUrlOperator	UrlUpdateSchedule;
	QPopupMenu*		pViewMenu;
	QPopupMenu*		pRemoteMenu;

public slots:
	void OnTimer();
	void OnListItemClicked(QListViewItem* item);
	void OnUrlFinished(QNetworkOperation* pNetwOp);
	void OnShowStationsMenu(int iID);
	void OnRemoteMenu(int iID);
	void OnGetUpdate();
};
