/********************************************************************************
** Form generated from reading UI file 'FMMainWindow.ui'
**
** Created by: Qt User Interface Compiler version 5.15.13
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_FMMAINWINDOW_H
#define UI_FMMAINWINDOW_H

#include <MultColorLED.h>
#include <QtCore/QVariant>
#include <QtGui/QIcon>
#include <QtWidgets/QAction>
#include <QtWidgets/QApplication>
#include <QtWidgets/QFrame>
#include <QtWidgets/QHBoxLayout>
#include <QtWidgets/QLabel>
#include <QtWidgets/QMainWindow>
#include <QtWidgets/QMenu>
#include <QtWidgets/QMenuBar>
#include <QtWidgets/QVBoxLayout>
#include <QtWidgets/QWidget>
#include "qwt_thermo.h"

QT_BEGIN_NAMESPACE

class Ui_FMMainWindow
{
public:
    QAction *actionTune;
    QAction *actionExit;
    QAction *actionAM;
    QAction *actionDRM;
    QAction *actionDisplayColor;
    QAction *actionWhats_This;
    QAction *actionAbout_Dream;
    QWidget *centralwidget;
    QVBoxLayout *verticalLayout;
    QFrame *FrameMainDisplay;
    QHBoxLayout *_6;
    QVBoxLayout *_7;
    QLabel *TextLabelInputLevel;
    QVBoxLayout *_8;
    QwtThermo *ProgrInputLevel;
    QHBoxLayout *_9;
    CMultColorLED *CLED_FAC;
    CMultColorLED *CLED_SDC;
    CMultColorLED *CLED_MSC;
    QVBoxLayout *_10;
    QFrame *FrameAudioDataParams;
    QHBoxLayout *_11;
    QLabel *LabelBitrate;
    QLabel *LabelCodec;
    QLabel *LabelStereoMono;
    QLabel *LabelServiceLabel;
    QHBoxLayout *_12;
    QLabel *LabelLanguage;
    QLabel *LabelCountryCode;
    QHBoxLayout *_13;
    QLabel *LabelProgrType;
    QLabel *LabelServiceID;
    QMenuBar *menubar;
    QMenu *menu_View;
    QMenu *menu_Settings;
    QMenu *menuHelp;

    void setupUi(QMainWindow *FMMainWindow)
    {
        if (FMMainWindow->objectName().isEmpty())
            FMMainWindow->setObjectName(QString::fromUtf8("FMMainWindow"));
        FMMainWindow->resize(416, 169);
        QIcon icon;
        icon.addFile(QString::fromUtf8(":/icons/MainIcon.svg"), QSize(), QIcon::Normal, QIcon::Off);
        FMMainWindow->setWindowIcon(icon);
        actionTune = new QAction(FMMainWindow);
        actionTune->setObjectName(QString::fromUtf8("actionTune"));
        actionExit = new QAction(FMMainWindow);
        actionExit->setObjectName(QString::fromUtf8("actionExit"));
        actionAM = new QAction(FMMainWindow);
        actionAM->setObjectName(QString::fromUtf8("actionAM"));
        actionDRM = new QAction(FMMainWindow);
        actionDRM->setObjectName(QString::fromUtf8("actionDRM"));
        actionDisplayColor = new QAction(FMMainWindow);
        actionDisplayColor->setObjectName(QString::fromUtf8("actionDisplayColor"));
        actionWhats_This = new QAction(FMMainWindow);
        actionWhats_This->setObjectName(QString::fromUtf8("actionWhats_This"));
        actionAbout_Dream = new QAction(FMMainWindow);
        actionAbout_Dream->setObjectName(QString::fromUtf8("actionAbout_Dream"));
        centralwidget = new QWidget(FMMainWindow);
        centralwidget->setObjectName(QString::fromUtf8("centralwidget"));
        verticalLayout = new QVBoxLayout(centralwidget);
        verticalLayout->setObjectName(QString::fromUtf8("verticalLayout"));
        FrameMainDisplay = new QFrame(centralwidget);
        FrameMainDisplay->setObjectName(QString::fromUtf8("FrameMainDisplay"));
        QSizePolicy sizePolicy(QSizePolicy::Expanding, QSizePolicy::Minimum);
        sizePolicy.setHorizontalStretch(0);
        sizePolicy.setVerticalStretch(0);
        sizePolicy.setHeightForWidth(FrameMainDisplay->sizePolicy().hasHeightForWidth());
        FrameMainDisplay->setSizePolicy(sizePolicy);
        QPalette palette;
        QBrush brush(QColor(255, 0, 0, 255));
        brush.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette.setBrush(QPalette::Active, QPalette::Button, brush);
        QBrush brush1(QColor(255, 127, 127, 255));
        brush1.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::Light, brush1);
        QBrush brush2(QColor(255, 63, 63, 255));
        brush2.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::Midlight, brush2);
        QBrush brush3(QColor(127, 0, 0, 255));
        brush3.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::Dark, brush3);
        QBrush brush4(QColor(170, 0, 0, 255));
        brush4.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::Mid, brush4);
        QBrush brush5(QColor(0, 0, 0, 255));
        brush5.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::Text, brush5);
        QBrush brush6(QColor(255, 255, 255, 255));
        brush6.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::BrightText, brush6);
        palette.setBrush(QPalette::Active, QPalette::ButtonText, brush5);
        palette.setBrush(QPalette::Active, QPalette::Base, brush6);
        palette.setBrush(QPalette::Active, QPalette::Window, brush5);
        palette.setBrush(QPalette::Active, QPalette::Shadow, brush5);
        QBrush brush7(QColor(0, 0, 128, 255));
        brush7.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::Highlight, brush7);
        palette.setBrush(QPalette::Active, QPalette::HighlightedText, brush6);
        palette.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette.setBrush(QPalette::Inactive, QPalette::Button, brush);
        palette.setBrush(QPalette::Inactive, QPalette::Light, brush1);
        QBrush brush8(QColor(255, 38, 38, 255));
        brush8.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Inactive, QPalette::Midlight, brush8);
        palette.setBrush(QPalette::Inactive, QPalette::Dark, brush3);
        palette.setBrush(QPalette::Inactive, QPalette::Mid, brush4);
        palette.setBrush(QPalette::Inactive, QPalette::Text, brush5);
        palette.setBrush(QPalette::Inactive, QPalette::BrightText, brush6);
        palette.setBrush(QPalette::Inactive, QPalette::ButtonText, brush5);
        palette.setBrush(QPalette::Inactive, QPalette::Base, brush6);
        palette.setBrush(QPalette::Inactive, QPalette::Window, brush5);
        palette.setBrush(QPalette::Inactive, QPalette::Shadow, brush5);
        palette.setBrush(QPalette::Inactive, QPalette::Highlight, brush7);
        palette.setBrush(QPalette::Inactive, QPalette::HighlightedText, brush6);
        QBrush brush9(QColor(128, 128, 128, 255));
        brush9.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Disabled, QPalette::WindowText, brush9);
        palette.setBrush(QPalette::Disabled, QPalette::Button, brush);
        palette.setBrush(QPalette::Disabled, QPalette::Light, brush1);
        palette.setBrush(QPalette::Disabled, QPalette::Midlight, brush8);
        palette.setBrush(QPalette::Disabled, QPalette::Dark, brush3);
        palette.setBrush(QPalette::Disabled, QPalette::Mid, brush4);
        palette.setBrush(QPalette::Disabled, QPalette::Text, brush5);
        palette.setBrush(QPalette::Disabled, QPalette::BrightText, brush6);
        palette.setBrush(QPalette::Disabled, QPalette::ButtonText, brush9);
        palette.setBrush(QPalette::Disabled, QPalette::Base, brush6);
        palette.setBrush(QPalette::Disabled, QPalette::Window, brush5);
        palette.setBrush(QPalette::Disabled, QPalette::Shadow, brush5);
        palette.setBrush(QPalette::Disabled, QPalette::Highlight, brush7);
        palette.setBrush(QPalette::Disabled, QPalette::HighlightedText, brush6);
        FrameMainDisplay->setPalette(palette);
        FrameMainDisplay->setAutoFillBackground(true);
        FrameMainDisplay->setFrameShape(QFrame::StyledPanel);
        FrameMainDisplay->setFrameShadow(QFrame::Raised);
        FrameMainDisplay->setLineWidth(1);
        _6 = new QHBoxLayout(FrameMainDisplay);
#ifndef Q_OS_MAC
        _6->setSpacing(6);
#endif
        _6->setContentsMargins(6, 6, 6, 6);
        _6->setObjectName(QString::fromUtf8("_6"));
        _7 = new QVBoxLayout();
#ifndef Q_OS_MAC
        _7->setSpacing(6);
#endif
#ifndef Q_OS_MAC
        _7->setContentsMargins(0, 0, 0, 0);
#endif
        _7->setObjectName(QString::fromUtf8("_7"));
        TextLabelInputLevel = new QLabel(FrameMainDisplay);
        TextLabelInputLevel->setObjectName(QString::fromUtf8("TextLabelInputLevel"));
        QSizePolicy sizePolicy1(QSizePolicy::Minimum, QSizePolicy::Minimum);
        sizePolicy1.setHorizontalStretch(0);
        sizePolicy1.setVerticalStretch(0);
        sizePolicy1.setHeightForWidth(TextLabelInputLevel->sizePolicy().hasHeightForWidth());
        TextLabelInputLevel->setSizePolicy(sizePolicy1);
        QPalette palette1;
        palette1.setBrush(QPalette::Active, QPalette::WindowText, brush);
        QBrush brush10(QColor(169, 134, 107, 255));
        brush10.setStyle(Qt::SolidPattern);
        palette1.setBrush(QPalette::Active, QPalette::Button, brush10);
        QBrush brush11(QColor(253, 200, 160, 255));
        brush11.setStyle(Qt::SolidPattern);
        palette1.setBrush(QPalette::Active, QPalette::Light, brush11);
        QBrush brush12(QColor(211, 167, 133, 255));
        brush12.setStyle(Qt::SolidPattern);
        palette1.setBrush(QPalette::Active, QPalette::Midlight, brush12);
        QBrush brush13(QColor(84, 66, 53, 255));
        brush13.setStyle(Qt::SolidPattern);
        palette1.setBrush(QPalette::Active, QPalette::Dark, brush13);
        QBrush brush14(QColor(112, 89, 71, 255));
        brush14.setStyle(Qt::SolidPattern);
        palette1.setBrush(QPalette::Active, QPalette::Mid, brush14);
        palette1.setBrush(QPalette::Active, QPalette::Text, brush5);
        palette1.setBrush(QPalette::Active, QPalette::BrightText, brush6);
        palette1.setBrush(QPalette::Active, QPalette::ButtonText, brush5);
        palette1.setBrush(QPalette::Active, QPalette::Base, brush6);
        palette1.setBrush(QPalette::Active, QPalette::Window, brush5);
        palette1.setBrush(QPalette::Active, QPalette::Shadow, brush5);
        palette1.setBrush(QPalette::Active, QPalette::Highlight, brush7);
        palette1.setBrush(QPalette::Active, QPalette::HighlightedText, brush6);
        palette1.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette1.setBrush(QPalette::Inactive, QPalette::Button, brush10);
        palette1.setBrush(QPalette::Inactive, QPalette::Light, brush11);
        QBrush brush15(QColor(194, 153, 122, 255));
        brush15.setStyle(Qt::SolidPattern);
        palette1.setBrush(QPalette::Inactive, QPalette::Midlight, brush15);
        palette1.setBrush(QPalette::Inactive, QPalette::Dark, brush13);
        palette1.setBrush(QPalette::Inactive, QPalette::Mid, brush14);
        palette1.setBrush(QPalette::Inactive, QPalette::Text, brush5);
        palette1.setBrush(QPalette::Inactive, QPalette::BrightText, brush6);
        palette1.setBrush(QPalette::Inactive, QPalette::ButtonText, brush5);
        palette1.setBrush(QPalette::Inactive, QPalette::Base, brush6);
        palette1.setBrush(QPalette::Inactive, QPalette::Window, brush5);
        palette1.setBrush(QPalette::Inactive, QPalette::Shadow, brush5);
        palette1.setBrush(QPalette::Inactive, QPalette::Highlight, brush7);
        palette1.setBrush(QPalette::Inactive, QPalette::HighlightedText, brush6);
        palette1.setBrush(QPalette::Disabled, QPalette::WindowText, brush9);
        palette1.setBrush(QPalette::Disabled, QPalette::Button, brush10);
        palette1.setBrush(QPalette::Disabled, QPalette::Light, brush11);
        palette1.setBrush(QPalette::Disabled, QPalette::Midlight, brush15);
        palette1.setBrush(QPalette::Disabled, QPalette::Dark, brush13);
        palette1.setBrush(QPalette::Disabled, QPalette::Mid, brush14);
        palette1.setBrush(QPalette::Disabled, QPalette::Text, brush5);
        palette1.setBrush(QPalette::Disabled, QPalette::BrightText, brush6);
        palette1.setBrush(QPalette::Disabled, QPalette::ButtonText, brush9);
        palette1.setBrush(QPalette::Disabled, QPalette::Base, brush6);
        palette1.setBrush(QPalette::Disabled, QPalette::Window, brush5);
        palette1.setBrush(QPalette::Disabled, QPalette::Shadow, brush5);
        palette1.setBrush(QPalette::Disabled, QPalette::Highlight, brush7);
        palette1.setBrush(QPalette::Disabled, QPalette::HighlightedText, brush6);
        TextLabelInputLevel->setPalette(palette1);
        QFont font;
        font.setFamily(QString::fromUtf8("Arial"));
        font.setPointSize(7);
        font.setBold(true);
        font.setWeight(75);
        TextLabelInputLevel->setFont(font);
        TextLabelInputLevel->setLineWidth(1);
        TextLabelInputLevel->setAlignment(Qt::AlignCenter);
        TextLabelInputLevel->setWordWrap(false);
        TextLabelInputLevel->setMargin(0);

        _7->addWidget(TextLabelInputLevel);

        _8 = new QVBoxLayout();
#ifndef Q_OS_MAC
        _8->setSpacing(6);
#endif
        _8->setContentsMargins(0, 0, 0, 0);
        _8->setObjectName(QString::fromUtf8("_8"));
        ProgrInputLevel = new QwtThermo(FrameMainDisplay);
        ProgrInputLevel->setObjectName(QString::fromUtf8("ProgrInputLevel"));
        sizePolicy1.setHeightForWidth(ProgrInputLevel->sizePolicy().hasHeightForWidth());
        ProgrInputLevel->setSizePolicy(sizePolicy1);
        QPalette palette2;
        palette2.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette2.setBrush(QPalette::Active, QPalette::Button, brush);
        palette2.setBrush(QPalette::Active, QPalette::Light, brush1);
        palette2.setBrush(QPalette::Active, QPalette::Midlight, brush2);
        palette2.setBrush(QPalette::Active, QPalette::Dark, brush3);
        palette2.setBrush(QPalette::Active, QPalette::Mid, brush4);
        palette2.setBrush(QPalette::Active, QPalette::Text, brush5);
        palette2.setBrush(QPalette::Active, QPalette::BrightText, brush6);
        palette2.setBrush(QPalette::Active, QPalette::ButtonText, brush5);
        palette2.setBrush(QPalette::Active, QPalette::Base, brush6);
        palette2.setBrush(QPalette::Active, QPalette::Window, brush5);
        palette2.setBrush(QPalette::Active, QPalette::Shadow, brush5);
        palette2.setBrush(QPalette::Active, QPalette::Highlight, brush7);
        palette2.setBrush(QPalette::Active, QPalette::HighlightedText, brush6);
        palette2.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette2.setBrush(QPalette::Inactive, QPalette::Button, brush);
        palette2.setBrush(QPalette::Inactive, QPalette::Light, brush1);
        palette2.setBrush(QPalette::Inactive, QPalette::Midlight, brush8);
        palette2.setBrush(QPalette::Inactive, QPalette::Dark, brush3);
        palette2.setBrush(QPalette::Inactive, QPalette::Mid, brush4);
        palette2.setBrush(QPalette::Inactive, QPalette::Text, brush5);
        palette2.setBrush(QPalette::Inactive, QPalette::BrightText, brush6);
        palette2.setBrush(QPalette::Inactive, QPalette::ButtonText, brush5);
        palette2.setBrush(QPalette::Inactive, QPalette::Base, brush6);
        palette2.setBrush(QPalette::Inactive, QPalette::Window, brush5);
        palette2.setBrush(QPalette::Inactive, QPalette::Shadow, brush5);
        palette2.setBrush(QPalette::Inactive, QPalette::Highlight, brush7);
        palette2.setBrush(QPalette::Inactive, QPalette::HighlightedText, brush6);
        palette2.setBrush(QPalette::Disabled, QPalette::WindowText, brush9);
        palette2.setBrush(QPalette::Disabled, QPalette::Button, brush);
        palette2.setBrush(QPalette::Disabled, QPalette::Light, brush1);
        palette2.setBrush(QPalette::Disabled, QPalette::Midlight, brush8);
        palette2.setBrush(QPalette::Disabled, QPalette::Dark, brush3);
        palette2.setBrush(QPalette::Disabled, QPalette::Mid, brush4);
        palette2.setBrush(QPalette::Disabled, QPalette::Text, brush5);
        palette2.setBrush(QPalette::Disabled, QPalette::BrightText, brush6);
        palette2.setBrush(QPalette::Disabled, QPalette::ButtonText, brush9);
        palette2.setBrush(QPalette::Disabled, QPalette::Base, brush6);
        palette2.setBrush(QPalette::Disabled, QPalette::Window, brush5);
        palette2.setBrush(QPalette::Disabled, QPalette::Shadow, brush5);
        palette2.setBrush(QPalette::Disabled, QPalette::Highlight, brush7);
        palette2.setBrush(QPalette::Disabled, QPalette::HighlightedText, brush6);
        ProgrInputLevel->setPalette(palette2);

        _8->addWidget(ProgrInputLevel);

        _9 = new QHBoxLayout();
        _9->setSpacing(0);
        _9->setContentsMargins(0, 0, 0, 0);
        _9->setObjectName(QString::fromUtf8("_9"));
        CLED_FAC = new CMultColorLED(FrameMainDisplay);
        CLED_FAC->setObjectName(QString::fromUtf8("CLED_FAC"));
        QSizePolicy sizePolicy2(QSizePolicy::Fixed, QSizePolicy::Fixed);
        sizePolicy2.setHorizontalStretch(0);
        sizePolicy2.setVerticalStretch(0);
        sizePolicy2.setHeightForWidth(CLED_FAC->sizePolicy().hasHeightForWidth());
        CLED_FAC->setSizePolicy(sizePolicy2);
        CLED_FAC->setMinimumSize(QSize(13, 7));
        CLED_FAC->setMaximumSize(QSize(13, 7));
        QPalette palette3;
        palette3.setBrush(QPalette::Active, QPalette::WindowText, brush5);
        palette3.setBrush(QPalette::Active, QPalette::Button, brush);
        palette3.setBrush(QPalette::Active, QPalette::Light, brush1);
        palette3.setBrush(QPalette::Active, QPalette::Midlight, brush2);
        palette3.setBrush(QPalette::Active, QPalette::Dark, brush3);
        palette3.setBrush(QPalette::Active, QPalette::Mid, brush4);
        palette3.setBrush(QPalette::Active, QPalette::Text, brush5);
        palette3.setBrush(QPalette::Active, QPalette::BrightText, brush6);
        palette3.setBrush(QPalette::Active, QPalette::ButtonText, brush5);
        palette3.setBrush(QPalette::Active, QPalette::Base, brush6);
        palette3.setBrush(QPalette::Active, QPalette::Window, brush5);
        palette3.setBrush(QPalette::Active, QPalette::Shadow, brush5);
        palette3.setBrush(QPalette::Active, QPalette::Highlight, brush7);
        palette3.setBrush(QPalette::Active, QPalette::HighlightedText, brush6);
        palette3.setBrush(QPalette::Inactive, QPalette::WindowText, brush5);
        palette3.setBrush(QPalette::Inactive, QPalette::Button, brush);
        palette3.setBrush(QPalette::Inactive, QPalette::Light, brush1);
        palette3.setBrush(QPalette::Inactive, QPalette::Midlight, brush8);
        palette3.setBrush(QPalette::Inactive, QPalette::Dark, brush3);
        palette3.setBrush(QPalette::Inactive, QPalette::Mid, brush4);
        palette3.setBrush(QPalette::Inactive, QPalette::Text, brush5);
        palette3.setBrush(QPalette::Inactive, QPalette::BrightText, brush6);
        palette3.setBrush(QPalette::Inactive, QPalette::ButtonText, brush5);
        palette3.setBrush(QPalette::Inactive, QPalette::Base, brush6);
        palette3.setBrush(QPalette::Inactive, QPalette::Window, brush5);
        palette3.setBrush(QPalette::Inactive, QPalette::Shadow, brush5);
        palette3.setBrush(QPalette::Inactive, QPalette::Highlight, brush7);
        palette3.setBrush(QPalette::Inactive, QPalette::HighlightedText, brush6);
        palette3.setBrush(QPalette::Disabled, QPalette::WindowText, brush9);
        palette3.setBrush(QPalette::Disabled, QPalette::Button, brush);
        palette3.setBrush(QPalette::Disabled, QPalette::Light, brush1);
        palette3.setBrush(QPalette::Disabled, QPalette::Midlight, brush8);
        palette3.setBrush(QPalette::Disabled, QPalette::Dark, brush3);
        palette3.setBrush(QPalette::Disabled, QPalette::Mid, brush4);
        palette3.setBrush(QPalette::Disabled, QPalette::Text, brush5);
        palette3.setBrush(QPalette::Disabled, QPalette::BrightText, brush6);
        palette3.setBrush(QPalette::Disabled, QPalette::ButtonText, brush9);
        palette3.setBrush(QPalette::Disabled, QPalette::Base, brush6);
        palette3.setBrush(QPalette::Disabled, QPalette::Window, brush5);
        palette3.setBrush(QPalette::Disabled, QPalette::Shadow, brush5);
        palette3.setBrush(QPalette::Disabled, QPalette::Highlight, brush7);
        palette3.setBrush(QPalette::Disabled, QPalette::HighlightedText, brush6);
        CLED_FAC->setPalette(palette3);

        _9->addWidget(CLED_FAC);

        CLED_SDC = new CMultColorLED(FrameMainDisplay);
        CLED_SDC->setObjectName(QString::fromUtf8("CLED_SDC"));
        sizePolicy2.setHeightForWidth(CLED_SDC->sizePolicy().hasHeightForWidth());
        CLED_SDC->setSizePolicy(sizePolicy2);
        CLED_SDC->setMinimumSize(QSize(13, 7));
        CLED_SDC->setMaximumSize(QSize(13, 7));
        QPalette palette4;
        palette4.setBrush(QPalette::Active, QPalette::WindowText, brush5);
        palette4.setBrush(QPalette::Active, QPalette::Button, brush);
        palette4.setBrush(QPalette::Active, QPalette::Light, brush1);
        palette4.setBrush(QPalette::Active, QPalette::Midlight, brush2);
        palette4.setBrush(QPalette::Active, QPalette::Dark, brush3);
        palette4.setBrush(QPalette::Active, QPalette::Mid, brush4);
        palette4.setBrush(QPalette::Active, QPalette::Text, brush5);
        palette4.setBrush(QPalette::Active, QPalette::BrightText, brush6);
        palette4.setBrush(QPalette::Active, QPalette::ButtonText, brush5);
        palette4.setBrush(QPalette::Active, QPalette::Base, brush6);
        palette4.setBrush(QPalette::Active, QPalette::Window, brush5);
        palette4.setBrush(QPalette::Active, QPalette::Shadow, brush5);
        palette4.setBrush(QPalette::Active, QPalette::Highlight, brush7);
        palette4.setBrush(QPalette::Active, QPalette::HighlightedText, brush6);
        palette4.setBrush(QPalette::Inactive, QPalette::WindowText, brush5);
        palette4.setBrush(QPalette::Inactive, QPalette::Button, brush);
        palette4.setBrush(QPalette::Inactive, QPalette::Light, brush1);
        palette4.setBrush(QPalette::Inactive, QPalette::Midlight, brush8);
        palette4.setBrush(QPalette::Inactive, QPalette::Dark, brush3);
        palette4.setBrush(QPalette::Inactive, QPalette::Mid, brush4);
        palette4.setBrush(QPalette::Inactive, QPalette::Text, brush5);
        palette4.setBrush(QPalette::Inactive, QPalette::BrightText, brush6);
        palette4.setBrush(QPalette::Inactive, QPalette::ButtonText, brush5);
        palette4.setBrush(QPalette::Inactive, QPalette::Base, brush6);
        palette4.setBrush(QPalette::Inactive, QPalette::Window, brush5);
        palette4.setBrush(QPalette::Inactive, QPalette::Shadow, brush5);
        palette4.setBrush(QPalette::Inactive, QPalette::Highlight, brush7);
        palette4.setBrush(QPalette::Inactive, QPalette::HighlightedText, brush6);
        palette4.setBrush(QPalette::Disabled, QPalette::WindowText, brush9);
        palette4.setBrush(QPalette::Disabled, QPalette::Button, brush);
        palette4.setBrush(QPalette::Disabled, QPalette::Light, brush1);
        palette4.setBrush(QPalette::Disabled, QPalette::Midlight, brush8);
        palette4.setBrush(QPalette::Disabled, QPalette::Dark, brush3);
        palette4.setBrush(QPalette::Disabled, QPalette::Mid, brush4);
        palette4.setBrush(QPalette::Disabled, QPalette::Text, brush5);
        palette4.setBrush(QPalette::Disabled, QPalette::BrightText, brush6);
        palette4.setBrush(QPalette::Disabled, QPalette::ButtonText, brush9);
        palette4.setBrush(QPalette::Disabled, QPalette::Base, brush6);
        palette4.setBrush(QPalette::Disabled, QPalette::Window, brush5);
        palette4.setBrush(QPalette::Disabled, QPalette::Shadow, brush5);
        palette4.setBrush(QPalette::Disabled, QPalette::Highlight, brush7);
        palette4.setBrush(QPalette::Disabled, QPalette::HighlightedText, brush6);
        CLED_SDC->setPalette(palette4);

        _9->addWidget(CLED_SDC);

        CLED_MSC = new CMultColorLED(FrameMainDisplay);
        CLED_MSC->setObjectName(QString::fromUtf8("CLED_MSC"));
        sizePolicy2.setHeightForWidth(CLED_MSC->sizePolicy().hasHeightForWidth());
        CLED_MSC->setSizePolicy(sizePolicy2);
        CLED_MSC->setMinimumSize(QSize(13, 7));
        CLED_MSC->setMaximumSize(QSize(13, 7));
        QPalette palette5;
        palette5.setBrush(QPalette::Active, QPalette::WindowText, brush5);
        palette5.setBrush(QPalette::Active, QPalette::Button, brush);
        palette5.setBrush(QPalette::Active, QPalette::Light, brush1);
        palette5.setBrush(QPalette::Active, QPalette::Midlight, brush2);
        palette5.setBrush(QPalette::Active, QPalette::Dark, brush3);
        palette5.setBrush(QPalette::Active, QPalette::Mid, brush4);
        palette5.setBrush(QPalette::Active, QPalette::Text, brush5);
        palette5.setBrush(QPalette::Active, QPalette::BrightText, brush6);
        palette5.setBrush(QPalette::Active, QPalette::ButtonText, brush5);
        palette5.setBrush(QPalette::Active, QPalette::Base, brush6);
        palette5.setBrush(QPalette::Active, QPalette::Window, brush5);
        palette5.setBrush(QPalette::Active, QPalette::Shadow, brush5);
        palette5.setBrush(QPalette::Active, QPalette::Highlight, brush7);
        palette5.setBrush(QPalette::Active, QPalette::HighlightedText, brush6);
        palette5.setBrush(QPalette::Inactive, QPalette::WindowText, brush5);
        palette5.setBrush(QPalette::Inactive, QPalette::Button, brush);
        palette5.setBrush(QPalette::Inactive, QPalette::Light, brush1);
        palette5.setBrush(QPalette::Inactive, QPalette::Midlight, brush8);
        palette5.setBrush(QPalette::Inactive, QPalette::Dark, brush3);
        palette5.setBrush(QPalette::Inactive, QPalette::Mid, brush4);
        palette5.setBrush(QPalette::Inactive, QPalette::Text, brush5);
        palette5.setBrush(QPalette::Inactive, QPalette::BrightText, brush6);
        palette5.setBrush(QPalette::Inactive, QPalette::ButtonText, brush5);
        palette5.setBrush(QPalette::Inactive, QPalette::Base, brush6);
        palette5.setBrush(QPalette::Inactive, QPalette::Window, brush5);
        palette5.setBrush(QPalette::Inactive, QPalette::Shadow, brush5);
        palette5.setBrush(QPalette::Inactive, QPalette::Highlight, brush7);
        palette5.setBrush(QPalette::Inactive, QPalette::HighlightedText, brush6);
        palette5.setBrush(QPalette::Disabled, QPalette::WindowText, brush9);
        palette5.setBrush(QPalette::Disabled, QPalette::Button, brush);
        palette5.setBrush(QPalette::Disabled, QPalette::Light, brush1);
        palette5.setBrush(QPalette::Disabled, QPalette::Midlight, brush8);
        palette5.setBrush(QPalette::Disabled, QPalette::Dark, brush3);
        palette5.setBrush(QPalette::Disabled, QPalette::Mid, brush4);
        palette5.setBrush(QPalette::Disabled, QPalette::Text, brush5);
        palette5.setBrush(QPalette::Disabled, QPalette::BrightText, brush6);
        palette5.setBrush(QPalette::Disabled, QPalette::ButtonText, brush9);
        palette5.setBrush(QPalette::Disabled, QPalette::Base, brush6);
        palette5.setBrush(QPalette::Disabled, QPalette::Window, brush5);
        palette5.setBrush(QPalette::Disabled, QPalette::Shadow, brush5);
        palette5.setBrush(QPalette::Disabled, QPalette::Highlight, brush7);
        palette5.setBrush(QPalette::Disabled, QPalette::HighlightedText, brush6);
        CLED_MSC->setPalette(palette5);

        _9->addWidget(CLED_MSC);


        _8->addLayout(_9);


        _7->addLayout(_8);


        _6->addLayout(_7);

        _10 = new QVBoxLayout();
        _10->setSpacing(1);
        _10->setContentsMargins(0, 0, 0, 0);
        _10->setObjectName(QString::fromUtf8("_10"));
        FrameAudioDataParams = new QFrame(FrameMainDisplay);
        FrameAudioDataParams->setObjectName(QString::fromUtf8("FrameAudioDataParams"));
        sizePolicy1.setHeightForWidth(FrameAudioDataParams->sizePolicy().hasHeightForWidth());
        FrameAudioDataParams->setSizePolicy(sizePolicy1);
        QPalette palette6;
        palette6.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette6.setBrush(QPalette::Active, QPalette::Button, brush);
        palette6.setBrush(QPalette::Active, QPalette::Light, brush1);
        palette6.setBrush(QPalette::Active, QPalette::Midlight, brush2);
        palette6.setBrush(QPalette::Active, QPalette::Dark, brush3);
        palette6.setBrush(QPalette::Active, QPalette::Mid, brush4);
        palette6.setBrush(QPalette::Active, QPalette::Text, brush6);
        palette6.setBrush(QPalette::Active, QPalette::BrightText, brush6);
        palette6.setBrush(QPalette::Active, QPalette::ButtonText, brush6);
        palette6.setBrush(QPalette::Active, QPalette::Base, brush5);
        palette6.setBrush(QPalette::Active, QPalette::Window, brush5);
        palette6.setBrush(QPalette::Active, QPalette::Shadow, brush5);
        palette6.setBrush(QPalette::Active, QPalette::Highlight, brush7);
        palette6.setBrush(QPalette::Active, QPalette::HighlightedText, brush6);
        palette6.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette6.setBrush(QPalette::Inactive, QPalette::Button, brush);
        palette6.setBrush(QPalette::Inactive, QPalette::Light, brush1);
        palette6.setBrush(QPalette::Inactive, QPalette::Midlight, brush8);
        palette6.setBrush(QPalette::Inactive, QPalette::Dark, brush3);
        palette6.setBrush(QPalette::Inactive, QPalette::Mid, brush4);
        palette6.setBrush(QPalette::Inactive, QPalette::Text, brush6);
        palette6.setBrush(QPalette::Inactive, QPalette::BrightText, brush6);
        palette6.setBrush(QPalette::Inactive, QPalette::ButtonText, brush6);
        palette6.setBrush(QPalette::Inactive, QPalette::Base, brush5);
        palette6.setBrush(QPalette::Inactive, QPalette::Window, brush5);
        palette6.setBrush(QPalette::Inactive, QPalette::Shadow, brush5);
        palette6.setBrush(QPalette::Inactive, QPalette::Highlight, brush7);
        palette6.setBrush(QPalette::Inactive, QPalette::HighlightedText, brush6);
        palette6.setBrush(QPalette::Disabled, QPalette::WindowText, brush9);
        palette6.setBrush(QPalette::Disabled, QPalette::Button, brush);
        palette6.setBrush(QPalette::Disabled, QPalette::Light, brush1);
        palette6.setBrush(QPalette::Disabled, QPalette::Midlight, brush8);
        palette6.setBrush(QPalette::Disabled, QPalette::Dark, brush3);
        palette6.setBrush(QPalette::Disabled, QPalette::Mid, brush4);
        palette6.setBrush(QPalette::Disabled, QPalette::Text, brush6);
        palette6.setBrush(QPalette::Disabled, QPalette::BrightText, brush6);
        palette6.setBrush(QPalette::Disabled, QPalette::ButtonText, brush9);
        palette6.setBrush(QPalette::Disabled, QPalette::Base, brush5);
        palette6.setBrush(QPalette::Disabled, QPalette::Window, brush5);
        palette6.setBrush(QPalette::Disabled, QPalette::Shadow, brush5);
        palette6.setBrush(QPalette::Disabled, QPalette::Highlight, brush7);
        palette6.setBrush(QPalette::Disabled, QPalette::HighlightedText, brush6);
        FrameAudioDataParams->setPalette(palette6);
        FrameAudioDataParams->setFrameShape(QFrame::Box);
        FrameAudioDataParams->setFrameShadow(QFrame::Plain);
        FrameAudioDataParams->setLineWidth(2);
        _11 = new QHBoxLayout(FrameAudioDataParams);
#ifndef Q_OS_MAC
        _11->setSpacing(6);
#endif
        _11->setContentsMargins(5, 5, 5, 5);
        _11->setObjectName(QString::fromUtf8("_11"));
        LabelBitrate = new QLabel(FrameAudioDataParams);
        LabelBitrate->setObjectName(QString::fromUtf8("LabelBitrate"));
        QPalette palette7;
        palette7.setBrush(QPalette::Active, QPalette::WindowText, brush);
        QBrush brush16(QColor(212, 208, 200, 255));
        brush16.setStyle(Qt::SolidPattern);
        palette7.setBrush(QPalette::Active, QPalette::Button, brush16);
        palette7.setBrush(QPalette::Active, QPalette::Light, brush6);
        QBrush brush17(QColor(233, 231, 227, 255));
        brush17.setStyle(Qt::SolidPattern);
        palette7.setBrush(QPalette::Active, QPalette::Midlight, brush17);
        QBrush brush18(QColor(106, 104, 100, 255));
        brush18.setStyle(Qt::SolidPattern);
        palette7.setBrush(QPalette::Active, QPalette::Dark, brush18);
        QBrush brush19(QColor(141, 138, 133, 255));
        brush19.setStyle(Qt::SolidPattern);
        palette7.setBrush(QPalette::Active, QPalette::Mid, brush19);
        palette7.setBrush(QPalette::Active, QPalette::Text, brush5);
        palette7.setBrush(QPalette::Active, QPalette::BrightText, brush6);
        palette7.setBrush(QPalette::Active, QPalette::ButtonText, brush5);
        palette7.setBrush(QPalette::Active, QPalette::Base, brush6);
        palette7.setBrush(QPalette::Active, QPalette::Window, brush5);
        palette7.setBrush(QPalette::Active, QPalette::Shadow, brush5);
        QBrush brush20(QColor(10, 36, 106, 255));
        brush20.setStyle(Qt::SolidPattern);
        palette7.setBrush(QPalette::Active, QPalette::Highlight, brush20);
        palette7.setBrush(QPalette::Active, QPalette::HighlightedText, brush6);
        palette7.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette7.setBrush(QPalette::Inactive, QPalette::Button, brush16);
        palette7.setBrush(QPalette::Inactive, QPalette::Light, brush6);
        QBrush brush21(QColor(243, 239, 230, 255));
        brush21.setStyle(Qt::SolidPattern);
        palette7.setBrush(QPalette::Inactive, QPalette::Midlight, brush21);
        palette7.setBrush(QPalette::Inactive, QPalette::Dark, brush18);
        palette7.setBrush(QPalette::Inactive, QPalette::Mid, brush19);
        palette7.setBrush(QPalette::Inactive, QPalette::Text, brush5);
        palette7.setBrush(QPalette::Inactive, QPalette::BrightText, brush6);
        palette7.setBrush(QPalette::Inactive, QPalette::ButtonText, brush5);
        palette7.setBrush(QPalette::Inactive, QPalette::Base, brush6);
        palette7.setBrush(QPalette::Inactive, QPalette::Window, brush5);
        palette7.setBrush(QPalette::Inactive, QPalette::Shadow, brush5);
        palette7.setBrush(QPalette::Inactive, QPalette::Highlight, brush20);
        palette7.setBrush(QPalette::Inactive, QPalette::HighlightedText, brush6);
        palette7.setBrush(QPalette::Disabled, QPalette::WindowText, brush9);
        palette7.setBrush(QPalette::Disabled, QPalette::Button, brush16);
        palette7.setBrush(QPalette::Disabled, QPalette::Light, brush6);
        palette7.setBrush(QPalette::Disabled, QPalette::Midlight, brush21);
        palette7.setBrush(QPalette::Disabled, QPalette::Dark, brush18);
        palette7.setBrush(QPalette::Disabled, QPalette::Mid, brush19);
        palette7.setBrush(QPalette::Disabled, QPalette::Text, brush5);
        palette7.setBrush(QPalette::Disabled, QPalette::BrightText, brush6);
        palette7.setBrush(QPalette::Disabled, QPalette::ButtonText, brush9);
        palette7.setBrush(QPalette::Disabled, QPalette::Base, brush6);
        palette7.setBrush(QPalette::Disabled, QPalette::Window, brush5);
        palette7.setBrush(QPalette::Disabled, QPalette::Shadow, brush5);
        palette7.setBrush(QPalette::Disabled, QPalette::Highlight, brush20);
        palette7.setBrush(QPalette::Disabled, QPalette::HighlightedText, brush6);
        LabelBitrate->setPalette(palette7);
        QFont font1;
        font1.setFamily(QString::fromUtf8("Arial"));
        font1.setPointSize(10);
        font1.setBold(true);
        font1.setWeight(75);
        LabelBitrate->setFont(font1);
        LabelBitrate->setAlignment(Qt::AlignCenter);
        LabelBitrate->setWordWrap(false);

        _11->addWidget(LabelBitrate);

        LabelCodec = new QLabel(FrameAudioDataParams);
        LabelCodec->setObjectName(QString::fromUtf8("LabelCodec"));
        QPalette palette8;
        palette8.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette8.setBrush(QPalette::Active, QPalette::Button, brush16);
        palette8.setBrush(QPalette::Active, QPalette::Light, brush6);
        palette8.setBrush(QPalette::Active, QPalette::Midlight, brush17);
        palette8.setBrush(QPalette::Active, QPalette::Dark, brush18);
        palette8.setBrush(QPalette::Active, QPalette::Mid, brush19);
        palette8.setBrush(QPalette::Active, QPalette::Text, brush5);
        palette8.setBrush(QPalette::Active, QPalette::BrightText, brush6);
        palette8.setBrush(QPalette::Active, QPalette::ButtonText, brush5);
        palette8.setBrush(QPalette::Active, QPalette::Base, brush6);
        palette8.setBrush(QPalette::Active, QPalette::Window, brush5);
        palette8.setBrush(QPalette::Active, QPalette::Shadow, brush5);
        palette8.setBrush(QPalette::Active, QPalette::Highlight, brush20);
        palette8.setBrush(QPalette::Active, QPalette::HighlightedText, brush6);
        palette8.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette8.setBrush(QPalette::Inactive, QPalette::Button, brush16);
        palette8.setBrush(QPalette::Inactive, QPalette::Light, brush6);
        palette8.setBrush(QPalette::Inactive, QPalette::Midlight, brush21);
        palette8.setBrush(QPalette::Inactive, QPalette::Dark, brush18);
        palette8.setBrush(QPalette::Inactive, QPalette::Mid, brush19);
        palette8.setBrush(QPalette::Inactive, QPalette::Text, brush5);
        palette8.setBrush(QPalette::Inactive, QPalette::BrightText, brush6);
        palette8.setBrush(QPalette::Inactive, QPalette::ButtonText, brush5);
        palette8.setBrush(QPalette::Inactive, QPalette::Base, brush6);
        palette8.setBrush(QPalette::Inactive, QPalette::Window, brush5);
        palette8.setBrush(QPalette::Inactive, QPalette::Shadow, brush5);
        palette8.setBrush(QPalette::Inactive, QPalette::Highlight, brush20);
        palette8.setBrush(QPalette::Inactive, QPalette::HighlightedText, brush6);
        palette8.setBrush(QPalette::Disabled, QPalette::WindowText, brush9);
        palette8.setBrush(QPalette::Disabled, QPalette::Button, brush16);
        palette8.setBrush(QPalette::Disabled, QPalette::Light, brush6);
        palette8.setBrush(QPalette::Disabled, QPalette::Midlight, brush21);
        palette8.setBrush(QPalette::Disabled, QPalette::Dark, brush18);
        palette8.setBrush(QPalette::Disabled, QPalette::Mid, brush19);
        palette8.setBrush(QPalette::Disabled, QPalette::Text, brush5);
        palette8.setBrush(QPalette::Disabled, QPalette::BrightText, brush6);
        palette8.setBrush(QPalette::Disabled, QPalette::ButtonText, brush9);
        palette8.setBrush(QPalette::Disabled, QPalette::Base, brush6);
        palette8.setBrush(QPalette::Disabled, QPalette::Window, brush5);
        palette8.setBrush(QPalette::Disabled, QPalette::Shadow, brush5);
        palette8.setBrush(QPalette::Disabled, QPalette::Highlight, brush20);
        palette8.setBrush(QPalette::Disabled, QPalette::HighlightedText, brush6);
        LabelCodec->setPalette(palette8);
        LabelCodec->setFont(font1);
        LabelCodec->setAlignment(Qt::AlignCenter);
        LabelCodec->setWordWrap(false);

        _11->addWidget(LabelCodec);

        LabelStereoMono = new QLabel(FrameAudioDataParams);
        LabelStereoMono->setObjectName(QString::fromUtf8("LabelStereoMono"));
        QPalette palette9;
        palette9.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette9.setBrush(QPalette::Active, QPalette::Button, brush16);
        palette9.setBrush(QPalette::Active, QPalette::Light, brush6);
        palette9.setBrush(QPalette::Active, QPalette::Midlight, brush17);
        palette9.setBrush(QPalette::Active, QPalette::Dark, brush18);
        palette9.setBrush(QPalette::Active, QPalette::Mid, brush19);
        palette9.setBrush(QPalette::Active, QPalette::Text, brush5);
        palette9.setBrush(QPalette::Active, QPalette::BrightText, brush6);
        palette9.setBrush(QPalette::Active, QPalette::ButtonText, brush5);
        palette9.setBrush(QPalette::Active, QPalette::Base, brush6);
        palette9.setBrush(QPalette::Active, QPalette::Window, brush5);
        palette9.setBrush(QPalette::Active, QPalette::Shadow, brush5);
        palette9.setBrush(QPalette::Active, QPalette::Highlight, brush20);
        palette9.setBrush(QPalette::Active, QPalette::HighlightedText, brush6);
        palette9.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette9.setBrush(QPalette::Inactive, QPalette::Button, brush16);
        palette9.setBrush(QPalette::Inactive, QPalette::Light, brush6);
        palette9.setBrush(QPalette::Inactive, QPalette::Midlight, brush21);
        palette9.setBrush(QPalette::Inactive, QPalette::Dark, brush18);
        palette9.setBrush(QPalette::Inactive, QPalette::Mid, brush19);
        palette9.setBrush(QPalette::Inactive, QPalette::Text, brush5);
        palette9.setBrush(QPalette::Inactive, QPalette::BrightText, brush6);
        palette9.setBrush(QPalette::Inactive, QPalette::ButtonText, brush5);
        palette9.setBrush(QPalette::Inactive, QPalette::Base, brush6);
        palette9.setBrush(QPalette::Inactive, QPalette::Window, brush5);
        palette9.setBrush(QPalette::Inactive, QPalette::Shadow, brush5);
        palette9.setBrush(QPalette::Inactive, QPalette::Highlight, brush20);
        palette9.setBrush(QPalette::Inactive, QPalette::HighlightedText, brush6);
        palette9.setBrush(QPalette::Disabled, QPalette::WindowText, brush9);
        palette9.setBrush(QPalette::Disabled, QPalette::Button, brush16);
        palette9.setBrush(QPalette::Disabled, QPalette::Light, brush6);
        palette9.setBrush(QPalette::Disabled, QPalette::Midlight, brush21);
        palette9.setBrush(QPalette::Disabled, QPalette::Dark, brush18);
        palette9.setBrush(QPalette::Disabled, QPalette::Mid, brush19);
        palette9.setBrush(QPalette::Disabled, QPalette::Text, brush5);
        palette9.setBrush(QPalette::Disabled, QPalette::BrightText, brush6);
        palette9.setBrush(QPalette::Disabled, QPalette::ButtonText, brush9);
        palette9.setBrush(QPalette::Disabled, QPalette::Base, brush6);
        palette9.setBrush(QPalette::Disabled, QPalette::Window, brush5);
        palette9.setBrush(QPalette::Disabled, QPalette::Shadow, brush5);
        palette9.setBrush(QPalette::Disabled, QPalette::Highlight, brush20);
        palette9.setBrush(QPalette::Disabled, QPalette::HighlightedText, brush6);
        LabelStereoMono->setPalette(palette9);
        LabelStereoMono->setFont(font1);
        LabelStereoMono->setAlignment(Qt::AlignCenter);
        LabelStereoMono->setWordWrap(false);

        _11->addWidget(LabelStereoMono);


        _10->addWidget(FrameAudioDataParams);

        LabelServiceLabel = new QLabel(FrameMainDisplay);
        LabelServiceLabel->setObjectName(QString::fromUtf8("LabelServiceLabel"));
        sizePolicy.setHeightForWidth(LabelServiceLabel->sizePolicy().hasHeightForWidth());
        LabelServiceLabel->setSizePolicy(sizePolicy);
        QPalette palette10;
        QBrush brush22(QColor(85, 255, 255, 255));
        brush22.setStyle(Qt::SolidPattern);
        palette10.setBrush(QPalette::Active, QPalette::WindowText, brush22);
        palette10.setBrush(QPalette::Active, QPalette::Button, brush10);
        palette10.setBrush(QPalette::Active, QPalette::Light, brush11);
        palette10.setBrush(QPalette::Active, QPalette::Midlight, brush12);
        palette10.setBrush(QPalette::Active, QPalette::Dark, brush13);
        palette10.setBrush(QPalette::Active, QPalette::Mid, brush14);
        palette10.setBrush(QPalette::Active, QPalette::Text, brush5);
        palette10.setBrush(QPalette::Active, QPalette::BrightText, brush6);
        palette10.setBrush(QPalette::Active, QPalette::ButtonText, brush5);
        palette10.setBrush(QPalette::Active, QPalette::Base, brush6);
        palette10.setBrush(QPalette::Active, QPalette::Window, brush5);
        palette10.setBrush(QPalette::Active, QPalette::Shadow, brush5);
        palette10.setBrush(QPalette::Active, QPalette::Highlight, brush7);
        palette10.setBrush(QPalette::Active, QPalette::HighlightedText, brush6);
        palette10.setBrush(QPalette::Inactive, QPalette::WindowText, brush22);
        palette10.setBrush(QPalette::Inactive, QPalette::Button, brush10);
        palette10.setBrush(QPalette::Inactive, QPalette::Light, brush11);
        palette10.setBrush(QPalette::Inactive, QPalette::Midlight, brush15);
        palette10.setBrush(QPalette::Inactive, QPalette::Dark, brush13);
        palette10.setBrush(QPalette::Inactive, QPalette::Mid, brush14);
        palette10.setBrush(QPalette::Inactive, QPalette::Text, brush5);
        palette10.setBrush(QPalette::Inactive, QPalette::BrightText, brush6);
        palette10.setBrush(QPalette::Inactive, QPalette::ButtonText, brush5);
        palette10.setBrush(QPalette::Inactive, QPalette::Base, brush6);
        palette10.setBrush(QPalette::Inactive, QPalette::Window, brush5);
        palette10.setBrush(QPalette::Inactive, QPalette::Shadow, brush5);
        palette10.setBrush(QPalette::Inactive, QPalette::Highlight, brush7);
        palette10.setBrush(QPalette::Inactive, QPalette::HighlightedText, brush6);
        palette10.setBrush(QPalette::Disabled, QPalette::WindowText, brush9);
        palette10.setBrush(QPalette::Disabled, QPalette::Button, brush10);
        palette10.setBrush(QPalette::Disabled, QPalette::Light, brush11);
        palette10.setBrush(QPalette::Disabled, QPalette::Midlight, brush15);
        palette10.setBrush(QPalette::Disabled, QPalette::Dark, brush13);
        palette10.setBrush(QPalette::Disabled, QPalette::Mid, brush14);
        palette10.setBrush(QPalette::Disabled, QPalette::Text, brush5);
        palette10.setBrush(QPalette::Disabled, QPalette::BrightText, brush6);
        palette10.setBrush(QPalette::Disabled, QPalette::ButtonText, brush9);
        palette10.setBrush(QPalette::Disabled, QPalette::Base, brush6);
        palette10.setBrush(QPalette::Disabled, QPalette::Window, brush5);
        palette10.setBrush(QPalette::Disabled, QPalette::Shadow, brush5);
        palette10.setBrush(QPalette::Disabled, QPalette::Highlight, brush7);
        palette10.setBrush(QPalette::Disabled, QPalette::HighlightedText, brush6);
        LabelServiceLabel->setPalette(palette10);
        QFont font2;
        font2.setFamily(QString::fromUtf8("Arial"));
        font2.setPointSize(14);
        font2.setBold(true);
        font2.setWeight(75);
        LabelServiceLabel->setFont(font2);
        LabelServiceLabel->setAlignment(Qt::AlignBottom|Qt::AlignHCenter);
        LabelServiceLabel->setWordWrap(false);
        LabelServiceLabel->setMargin(0);
        LabelServiceLabel->setIndent(5);

        _10->addWidget(LabelServiceLabel);

        _12 = new QHBoxLayout();
        _12->setSpacing(2);
        _12->setContentsMargins(0, 0, 0, 0);
        _12->setObjectName(QString::fromUtf8("_12"));
        LabelLanguage = new QLabel(FrameMainDisplay);
        LabelLanguage->setObjectName(QString::fromUtf8("LabelLanguage"));
        sizePolicy.setHeightForWidth(LabelLanguage->sizePolicy().hasHeightForWidth());
        LabelLanguage->setSizePolicy(sizePolicy);
        QPalette palette11;
        palette11.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette11.setBrush(QPalette::Active, QPalette::Button, brush10);
        palette11.setBrush(QPalette::Active, QPalette::Light, brush11);
        palette11.setBrush(QPalette::Active, QPalette::Midlight, brush12);
        palette11.setBrush(QPalette::Active, QPalette::Dark, brush13);
        palette11.setBrush(QPalette::Active, QPalette::Mid, brush14);
        palette11.setBrush(QPalette::Active, QPalette::Text, brush5);
        palette11.setBrush(QPalette::Active, QPalette::BrightText, brush6);
        palette11.setBrush(QPalette::Active, QPalette::ButtonText, brush5);
        palette11.setBrush(QPalette::Active, QPalette::Base, brush6);
        palette11.setBrush(QPalette::Active, QPalette::Window, brush5);
        palette11.setBrush(QPalette::Active, QPalette::Shadow, brush5);
        palette11.setBrush(QPalette::Active, QPalette::Highlight, brush7);
        palette11.setBrush(QPalette::Active, QPalette::HighlightedText, brush6);
        palette11.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette11.setBrush(QPalette::Inactive, QPalette::Button, brush10);
        palette11.setBrush(QPalette::Inactive, QPalette::Light, brush11);
        palette11.setBrush(QPalette::Inactive, QPalette::Midlight, brush15);
        palette11.setBrush(QPalette::Inactive, QPalette::Dark, brush13);
        palette11.setBrush(QPalette::Inactive, QPalette::Mid, brush14);
        palette11.setBrush(QPalette::Inactive, QPalette::Text, brush5);
        palette11.setBrush(QPalette::Inactive, QPalette::BrightText, brush6);
        palette11.setBrush(QPalette::Inactive, QPalette::ButtonText, brush5);
        palette11.setBrush(QPalette::Inactive, QPalette::Base, brush6);
        palette11.setBrush(QPalette::Inactive, QPalette::Window, brush5);
        palette11.setBrush(QPalette::Inactive, QPalette::Shadow, brush5);
        palette11.setBrush(QPalette::Inactive, QPalette::Highlight, brush7);
        palette11.setBrush(QPalette::Inactive, QPalette::HighlightedText, brush6);
        palette11.setBrush(QPalette::Disabled, QPalette::WindowText, brush9);
        palette11.setBrush(QPalette::Disabled, QPalette::Button, brush10);
        palette11.setBrush(QPalette::Disabled, QPalette::Light, brush11);
        palette11.setBrush(QPalette::Disabled, QPalette::Midlight, brush15);
        palette11.setBrush(QPalette::Disabled, QPalette::Dark, brush13);
        palette11.setBrush(QPalette::Disabled, QPalette::Mid, brush14);
        palette11.setBrush(QPalette::Disabled, QPalette::Text, brush5);
        palette11.setBrush(QPalette::Disabled, QPalette::BrightText, brush6);
        palette11.setBrush(QPalette::Disabled, QPalette::ButtonText, brush9);
        palette11.setBrush(QPalette::Disabled, QPalette::Base, brush6);
        palette11.setBrush(QPalette::Disabled, QPalette::Window, brush5);
        palette11.setBrush(QPalette::Disabled, QPalette::Shadow, brush5);
        palette11.setBrush(QPalette::Disabled, QPalette::Highlight, brush7);
        palette11.setBrush(QPalette::Disabled, QPalette::HighlightedText, brush6);
        LabelLanguage->setPalette(palette11);
        LabelLanguage->setFont(font1);
        LabelLanguage->setLineWidth(1);
        LabelLanguage->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        LabelLanguage->setWordWrap(false);
        LabelLanguage->setMargin(0);

        _12->addWidget(LabelLanguage);

        LabelCountryCode = new QLabel(FrameMainDisplay);
        LabelCountryCode->setObjectName(QString::fromUtf8("LabelCountryCode"));
        sizePolicy.setHeightForWidth(LabelCountryCode->sizePolicy().hasHeightForWidth());
        LabelCountryCode->setSizePolicy(sizePolicy);
        QPalette palette12;
        palette12.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette12.setBrush(QPalette::Active, QPalette::Button, brush10);
        palette12.setBrush(QPalette::Active, QPalette::Light, brush11);
        palette12.setBrush(QPalette::Active, QPalette::Midlight, brush12);
        palette12.setBrush(QPalette::Active, QPalette::Dark, brush13);
        palette12.setBrush(QPalette::Active, QPalette::Mid, brush14);
        palette12.setBrush(QPalette::Active, QPalette::Text, brush5);
        palette12.setBrush(QPalette::Active, QPalette::BrightText, brush6);
        palette12.setBrush(QPalette::Active, QPalette::ButtonText, brush5);
        palette12.setBrush(QPalette::Active, QPalette::Base, brush6);
        palette12.setBrush(QPalette::Active, QPalette::Window, brush5);
        palette12.setBrush(QPalette::Active, QPalette::Shadow, brush5);
        palette12.setBrush(QPalette::Active, QPalette::Highlight, brush7);
        palette12.setBrush(QPalette::Active, QPalette::HighlightedText, brush6);
        palette12.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette12.setBrush(QPalette::Inactive, QPalette::Button, brush10);
        palette12.setBrush(QPalette::Inactive, QPalette::Light, brush11);
        palette12.setBrush(QPalette::Inactive, QPalette::Midlight, brush15);
        palette12.setBrush(QPalette::Inactive, QPalette::Dark, brush13);
        palette12.setBrush(QPalette::Inactive, QPalette::Mid, brush14);
        palette12.setBrush(QPalette::Inactive, QPalette::Text, brush5);
        palette12.setBrush(QPalette::Inactive, QPalette::BrightText, brush6);
        palette12.setBrush(QPalette::Inactive, QPalette::ButtonText, brush5);
        palette12.setBrush(QPalette::Inactive, QPalette::Base, brush6);
        palette12.setBrush(QPalette::Inactive, QPalette::Window, brush5);
        palette12.setBrush(QPalette::Inactive, QPalette::Shadow, brush5);
        palette12.setBrush(QPalette::Inactive, QPalette::Highlight, brush7);
        palette12.setBrush(QPalette::Inactive, QPalette::HighlightedText, brush6);
        palette12.setBrush(QPalette::Disabled, QPalette::WindowText, brush9);
        palette12.setBrush(QPalette::Disabled, QPalette::Button, brush10);
        palette12.setBrush(QPalette::Disabled, QPalette::Light, brush11);
        palette12.setBrush(QPalette::Disabled, QPalette::Midlight, brush15);
        palette12.setBrush(QPalette::Disabled, QPalette::Dark, brush13);
        palette12.setBrush(QPalette::Disabled, QPalette::Mid, brush14);
        palette12.setBrush(QPalette::Disabled, QPalette::Text, brush5);
        palette12.setBrush(QPalette::Disabled, QPalette::BrightText, brush6);
        palette12.setBrush(QPalette::Disabled, QPalette::ButtonText, brush9);
        palette12.setBrush(QPalette::Disabled, QPalette::Base, brush6);
        palette12.setBrush(QPalette::Disabled, QPalette::Window, brush5);
        palette12.setBrush(QPalette::Disabled, QPalette::Shadow, brush5);
        palette12.setBrush(QPalette::Disabled, QPalette::Highlight, brush7);
        palette12.setBrush(QPalette::Disabled, QPalette::HighlightedText, brush6);
        LabelCountryCode->setPalette(palette12);
        LabelCountryCode->setFont(font1);
        LabelCountryCode->setLineWidth(1);
        LabelCountryCode->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        LabelCountryCode->setWordWrap(false);
        LabelCountryCode->setMargin(0);

        _12->addWidget(LabelCountryCode);


        _10->addLayout(_12);

        _13 = new QHBoxLayout();
        _13->setSpacing(2);
        _13->setContentsMargins(0, 0, 0, 0);
        _13->setObjectName(QString::fromUtf8("_13"));
        LabelProgrType = new QLabel(FrameMainDisplay);
        LabelProgrType->setObjectName(QString::fromUtf8("LabelProgrType"));
        sizePolicy.setHeightForWidth(LabelProgrType->sizePolicy().hasHeightForWidth());
        LabelProgrType->setSizePolicy(sizePolicy);
        QPalette palette13;
        palette13.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette13.setBrush(QPalette::Active, QPalette::Button, brush10);
        palette13.setBrush(QPalette::Active, QPalette::Light, brush11);
        palette13.setBrush(QPalette::Active, QPalette::Midlight, brush12);
        palette13.setBrush(QPalette::Active, QPalette::Dark, brush13);
        palette13.setBrush(QPalette::Active, QPalette::Mid, brush14);
        palette13.setBrush(QPalette::Active, QPalette::Text, brush5);
        palette13.setBrush(QPalette::Active, QPalette::BrightText, brush6);
        palette13.setBrush(QPalette::Active, QPalette::ButtonText, brush5);
        palette13.setBrush(QPalette::Active, QPalette::Base, brush6);
        palette13.setBrush(QPalette::Active, QPalette::Window, brush5);
        palette13.setBrush(QPalette::Active, QPalette::Shadow, brush5);
        palette13.setBrush(QPalette::Active, QPalette::Highlight, brush7);
        palette13.setBrush(QPalette::Active, QPalette::HighlightedText, brush6);
        palette13.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette13.setBrush(QPalette::Inactive, QPalette::Button, brush10);
        palette13.setBrush(QPalette::Inactive, QPalette::Light, brush11);
        palette13.setBrush(QPalette::Inactive, QPalette::Midlight, brush15);
        palette13.setBrush(QPalette::Inactive, QPalette::Dark, brush13);
        palette13.setBrush(QPalette::Inactive, QPalette::Mid, brush14);
        palette13.setBrush(QPalette::Inactive, QPalette::Text, brush5);
        palette13.setBrush(QPalette::Inactive, QPalette::BrightText, brush6);
        palette13.setBrush(QPalette::Inactive, QPalette::ButtonText, brush5);
        palette13.setBrush(QPalette::Inactive, QPalette::Base, brush6);
        palette13.setBrush(QPalette::Inactive, QPalette::Window, brush5);
        palette13.setBrush(QPalette::Inactive, QPalette::Shadow, brush5);
        palette13.setBrush(QPalette::Inactive, QPalette::Highlight, brush7);
        palette13.setBrush(QPalette::Inactive, QPalette::HighlightedText, brush6);
        palette13.setBrush(QPalette::Disabled, QPalette::WindowText, brush9);
        palette13.setBrush(QPalette::Disabled, QPalette::Button, brush10);
        palette13.setBrush(QPalette::Disabled, QPalette::Light, brush11);
        palette13.setBrush(QPalette::Disabled, QPalette::Midlight, brush15);
        palette13.setBrush(QPalette::Disabled, QPalette::Dark, brush13);
        palette13.setBrush(QPalette::Disabled, QPalette::Mid, brush14);
        palette13.setBrush(QPalette::Disabled, QPalette::Text, brush5);
        palette13.setBrush(QPalette::Disabled, QPalette::BrightText, brush6);
        palette13.setBrush(QPalette::Disabled, QPalette::ButtonText, brush9);
        palette13.setBrush(QPalette::Disabled, QPalette::Base, brush6);
        palette13.setBrush(QPalette::Disabled, QPalette::Window, brush5);
        palette13.setBrush(QPalette::Disabled, QPalette::Shadow, brush5);
        palette13.setBrush(QPalette::Disabled, QPalette::Highlight, brush7);
        palette13.setBrush(QPalette::Disabled, QPalette::HighlightedText, brush6);
        LabelProgrType->setPalette(palette13);
        LabelProgrType->setFont(font1);
        LabelProgrType->setLineWidth(1);
        LabelProgrType->setAlignment(Qt::AlignBottom|Qt::AlignLeading|Qt::AlignLeft);
        LabelProgrType->setWordWrap(false);
        LabelProgrType->setMargin(0);
        LabelProgrType->setIndent(-1);

        _13->addWidget(LabelProgrType);

        LabelServiceID = new QLabel(FrameMainDisplay);
        LabelServiceID->setObjectName(QString::fromUtf8("LabelServiceID"));
        sizePolicy.setHeightForWidth(LabelServiceID->sizePolicy().hasHeightForWidth());
        LabelServiceID->setSizePolicy(sizePolicy);
        QPalette palette14;
        palette14.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette14.setBrush(QPalette::Active, QPalette::Button, brush10);
        palette14.setBrush(QPalette::Active, QPalette::Light, brush11);
        palette14.setBrush(QPalette::Active, QPalette::Midlight, brush12);
        palette14.setBrush(QPalette::Active, QPalette::Dark, brush13);
        palette14.setBrush(QPalette::Active, QPalette::Mid, brush14);
        palette14.setBrush(QPalette::Active, QPalette::Text, brush5);
        palette14.setBrush(QPalette::Active, QPalette::BrightText, brush6);
        palette14.setBrush(QPalette::Active, QPalette::ButtonText, brush5);
        palette14.setBrush(QPalette::Active, QPalette::Base, brush6);
        palette14.setBrush(QPalette::Active, QPalette::Window, brush5);
        palette14.setBrush(QPalette::Active, QPalette::Shadow, brush5);
        palette14.setBrush(QPalette::Active, QPalette::Highlight, brush7);
        palette14.setBrush(QPalette::Active, QPalette::HighlightedText, brush6);
        palette14.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette14.setBrush(QPalette::Inactive, QPalette::Button, brush10);
        palette14.setBrush(QPalette::Inactive, QPalette::Light, brush11);
        palette14.setBrush(QPalette::Inactive, QPalette::Midlight, brush15);
        palette14.setBrush(QPalette::Inactive, QPalette::Dark, brush13);
        palette14.setBrush(QPalette::Inactive, QPalette::Mid, brush14);
        palette14.setBrush(QPalette::Inactive, QPalette::Text, brush5);
        palette14.setBrush(QPalette::Inactive, QPalette::BrightText, brush6);
        palette14.setBrush(QPalette::Inactive, QPalette::ButtonText, brush5);
        palette14.setBrush(QPalette::Inactive, QPalette::Base, brush6);
        palette14.setBrush(QPalette::Inactive, QPalette::Window, brush5);
        palette14.setBrush(QPalette::Inactive, QPalette::Shadow, brush5);
        palette14.setBrush(QPalette::Inactive, QPalette::Highlight, brush7);
        palette14.setBrush(QPalette::Inactive, QPalette::HighlightedText, brush6);
        palette14.setBrush(QPalette::Disabled, QPalette::WindowText, brush9);
        palette14.setBrush(QPalette::Disabled, QPalette::Button, brush10);
        palette14.setBrush(QPalette::Disabled, QPalette::Light, brush11);
        palette14.setBrush(QPalette::Disabled, QPalette::Midlight, brush15);
        palette14.setBrush(QPalette::Disabled, QPalette::Dark, brush13);
        palette14.setBrush(QPalette::Disabled, QPalette::Mid, brush14);
        palette14.setBrush(QPalette::Disabled, QPalette::Text, brush5);
        palette14.setBrush(QPalette::Disabled, QPalette::BrightText, brush6);
        palette14.setBrush(QPalette::Disabled, QPalette::ButtonText, brush9);
        palette14.setBrush(QPalette::Disabled, QPalette::Base, brush6);
        palette14.setBrush(QPalette::Disabled, QPalette::Window, brush5);
        palette14.setBrush(QPalette::Disabled, QPalette::Shadow, brush5);
        palette14.setBrush(QPalette::Disabled, QPalette::Highlight, brush7);
        palette14.setBrush(QPalette::Disabled, QPalette::HighlightedText, brush6);
        LabelServiceID->setPalette(palette14);
        LabelServiceID->setFont(font1);
        LabelServiceID->setLineWidth(1);
        LabelServiceID->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        LabelServiceID->setWordWrap(false);
        LabelServiceID->setMargin(0);

        _13->addWidget(LabelServiceID);


        _10->addLayout(_13);


        _6->addLayout(_10);


        verticalLayout->addWidget(FrameMainDisplay);

        FMMainWindow->setCentralWidget(centralwidget);
        menubar = new QMenuBar(FMMainWindow);
        menubar->setObjectName(QString::fromUtf8("menubar"));
        menubar->setGeometry(QRect(0, 0, 416, 25));
        menu_View = new QMenu(menubar);
        menu_View->setObjectName(QString::fromUtf8("menu_View"));
        menu_Settings = new QMenu(menubar);
        menu_Settings->setObjectName(QString::fromUtf8("menu_Settings"));
        menuHelp = new QMenu(menubar);
        menuHelp->setObjectName(QString::fromUtf8("menuHelp"));
        FMMainWindow->setMenuBar(menubar);

        menubar->addAction(menu_View->menuAction());
        menubar->addAction(menu_Settings->menuAction());
        menubar->addAction(menuHelp->menuAction());
        menu_View->addAction(actionTune);
        menu_Settings->addAction(actionAM);
        menu_Settings->addAction(actionDRM);
        menu_Settings->addAction(actionDisplayColor);
        menuHelp->addAction(actionWhats_This);
        menuHelp->addSeparator();
        menuHelp->addAction(actionAbout_Dream);

        retranslateUi(FMMainWindow);

        QMetaObject::connectSlotsByName(FMMainWindow);
    } // setupUi

    void retranslateUi(QMainWindow *FMMainWindow)
    {
        FMMainWindow->setWindowTitle(QCoreApplication::translate("FMMainWindow", "FM Receiver", nullptr));
        actionTune->setText(QCoreApplication::translate("FMMainWindow", "Tune...", nullptr));
#if QT_CONFIG(shortcut)
        actionTune->setShortcut(QCoreApplication::translate("FMMainWindow", "Alt+T", nullptr));
#endif // QT_CONFIG(shortcut)
        actionExit->setText(QCoreApplication::translate("FMMainWindow", "E&xit", nullptr));
#if QT_CONFIG(shortcut)
        actionExit->setShortcut(QCoreApplication::translate("FMMainWindow", "Alt+X", nullptr));
#endif // QT_CONFIG(shortcut)
        actionAM->setText(QCoreApplication::translate("FMMainWindow", "AM (analog)", nullptr));
        actionDRM->setText(QCoreApplication::translate("FMMainWindow", "DRM (digital)", nullptr));
        actionDisplayColor->setText(QCoreApplication::translate("FMMainWindow", "Set Display Color", nullptr));
        actionWhats_This->setText(QCoreApplication::translate("FMMainWindow", "&Whats This", nullptr));
#if QT_CONFIG(shortcut)
        actionWhats_This->setShortcut(QCoreApplication::translate("FMMainWindow", "Shift+F1", nullptr));
#endif // QT_CONFIG(shortcut)
        actionAbout_Dream->setText(QCoreApplication::translate("FMMainWindow", "&About Dream...", nullptr));
        TextLabelInputLevel->setText(QCoreApplication::translate("FMMainWindow", "Level [dB]", nullptr));
        LabelBitrate->setText(QCoreApplication::translate("FMMainWindow", "15 kbps", nullptr));
        LabelCodec->setText(QCoreApplication::translate("FMMainWindow", "AAC+", nullptr));
        LabelStereoMono->setText(QCoreApplication::translate("FMMainWindow", "Stereo", nullptr));
        LabelServiceLabel->setText(QCoreApplication::translate("FMMainWindow", "Deutsche Welle", nullptr));
        LabelLanguage->setText(QCoreApplication::translate("FMMainWindow", "German", nullptr));
        LabelCountryCode->setText(QCoreApplication::translate("FMMainWindow", "DE", nullptr));
        LabelProgrType->setText(QCoreApplication::translate("FMMainWindow", "Information", nullptr));
        LabelServiceID->setText(QCoreApplication::translate("FMMainWindow", "1001", nullptr));
        menu_View->setTitle(QCoreApplication::translate("FMMainWindow", "&View", nullptr));
        menu_Settings->setTitle(QCoreApplication::translate("FMMainWindow", "&Settings", nullptr));
        menuHelp->setTitle(QCoreApplication::translate("FMMainWindow", "&Help", nullptr));
    } // retranslateUi

};

namespace Ui {
    class FMMainWindow: public Ui_FMMainWindow {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_FMMAINWINDOW_H
