/******************************************************************************\
 * Technische Universitaet Darmstadt, Institut fuer Nachrichtentechnik
 * Copyright (c) 2001
 *
 * Author(s):
 *	Volker Fischer
 *
 * Description:
 *	
 *
 ******************************************************************************
 *
 * This program is free software; you can redistribute it and/or modify it under
 * the terms of the GNU General Public License as published by the Free Software
 * Foundation; either version 2 of the License, or (at your option) any later 
 * version.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT 
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU General Public License for more 
 * details.
 *
 * You should have received a copy of the GNU General Public License along with
 * this program; if not, write to the Free Software Foundation, Inc., 
 * 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA
 *
\******************************************************************************/

#if !defined(CONNVOL_ENC_H__3B0BA660_CA63_4344_BB2B_23E7A0D31912__INCLUDED_)
#define CONNVOL_ENC_H__3B0BA660_CA63_4344_BB2B_23E7A0D31912__INCLUDED_

#include "../GlobalDefinitions.h"
#include "../tables/TableMLC.h"
#include "../Vector.h"
#include "../Parameter.h"


/* Classes ********************************************************************/
class CConvEncoder
{
public:
	CConvEncoder();
	virtual ~CConvEncoder() {}

	int		Encode(CVector<_BINARY>& vecInputData, 
				   CVector<_BINARY>& vecOutputData);
	_BINARY Convolution(const _BYTE byNewStateShiftReg, const int iGenPolyn) const;
	void	Init(CParameter::ECodScheme eNewCodingScheme,
				 CParameter::EChanType eNewChannelType,
				 int iN1, int iN2, int iNewNumInBitsPartA,
				 int iNewNumInBitsPartB, int iPunctPatPartA, int iPunctPatPartB,
				 int iLevel);

protected:
	int						iNumInBitsPartA;
	int						iNumInBits;
	int						iNumInBitsWithMemory;
	int						iPartAPatLen;
	CVector<int>			veciPuncPatPartA;
	int						iPartBPatLen;
	CVector<int>			veciPuncPatPartB;
	CVector<int>			veciTailBitPat;

	CParameter::EChanType	eChannelType;
};


/* Implementation *************************************************************/
inline _BINARY CConvEncoder::Convolution(const _BYTE byNewStateShiftReg,
										 const int iGenPolyn) const
{
	/* This table was generated by the code given in the constructor of class
	   "CConvEncoder" */
	static _BINARY vecbiConvTable[256] = {
		0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 
		1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 
		1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 
		0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 
		1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 
		0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 
		0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 
		1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 
		0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 
		1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 
		1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 
		0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 
		1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 
		0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 
		0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 
		1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1
	};

	/* Mask bits with generator polynomial and get convolution result from
	   pre-calculated table (speed optimization). Since we have a AND
	   operation on the "byGeneratorMatrix", the index of the convolution
	   table cannot exceed the size of the table (although the value in
	   "byNewStateShiftReg" can be larger) */
	return vecbiConvTable[byNewStateShiftReg & byGeneratorMatrix[iGenPolyn]];
}


#endif // !defined(CONNVOL_ENC_H__3B0BA660_CA63_4344_BB2B_23E7A0D31912__INCLUDED_)
